name: chocolatine

on:
  push:
    branches-ignore:
      - 'no-ga/**'
  pull_request:
    branches-ignore:
      - 'no-ga/**'

env:
  MIRROR_SSH_URL: "EpitechPGE1-2025/G-DOP-200-RUN-2-1-chocolatine-16"
  EXECUTABLES: "my_test"

jobs:
  check_compilation_and_coding_style:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest

    steps:
      - name: Checkout repository
        if: ${{ github.repository != env.MIRROR_SSH_URL }}
        uses: actions/checkout@v4

      - name: Compile project with epiclang
        if: ${{ github.repository != env.MIRROR_SSH_URL }}
        run: make CC=epiclang > epiclang_report.log 2>&1
        timeout-minutes: 2

      - name: Checking coding style
        if: ${{ github.repository != env.MIRROR_SSH_URL }}
        run: |
          grep '\[Banana\]' epiclang_report.log | grep -v '^epiclang' > filtered.log || true
          if [ -s filtered.log ]; then
            cat filtered.log
            echo "::error::Too many Codding Style"
            exit 84
          fi

      - name: Clean file
        if: ${{ github.repository != env.MIRROR_SSH_URL }}
        run: make clean

      - name: Verify Executables
        if: ${{ github.repository != env.MIRROR_SSH_URL }}
        run: |
          if [ ! -x $EXECUTABLES ]; then
            echo "::error::File not found or executable"
            exit 84
          fi
  
  run_tests:
    needs: check_compilation_and_coding_style
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest

    steps:
      - name: Checkout repository
        if: ${{ github.repository != env.MIRROR_SSH_URL }}
        uses: actions/checkout@v4

      - name: run_tests
        if: ${{ github.repository != env.MIRROR_SSH_URL }}
        run: make tests_run
        timeout-minutes: 2
      
      - name: run fclean
        if: ${{ github.repository != env.MIRROR_SSH_URL }}
        run: make fclean
  
  push_to_mirror:
    needs: run_tests
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        if: ${{ github.repository != env.MIRROR_SSH_URL }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Mirror
        if: ${{ github.repository != env.MIRROR_SSH_URL }}
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_SSH_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
          ssh_username: ${{ secrets.GIT_SSH_PRIVATE_KEY_ID }}
