name: Build Project with epiclang

on:
  push:
  pull_request:

jobs:
  check_compilation_and_coding_style:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checking coding style
        run: |
          make CC=epiclang > epiclang_report.log 2>&1
          grep '\[Banana\]' epiclang_report.log | grep -v '^epiclang' > filtered.log || true
          cat filtered.log
          if [ -s filtered.log ]; then
            echo filtered.log
            exit 84
          fi

      - name: Build Project
        run: |
          make
          if [ ! -f ./my_test ]; then
            echo "::error::Binary 'my_test' not found."
            exit 84
          fi

      - name: Exec Project
        run: ./my_test
